version: '3'
	

	services:
	    clickhouse-zookeeper:
	        image: zookeeper
	        ports:
	            - "2181:2181"
	            - "2182:2182"
	        container_name: clickhouse-zookeeper
	        hostname: clickhouse-zookeeper
	

	    clickhouse1:
	        image: yandex/clickhouse-server
	        hostname: clickhouse1
	        container_name: clickhouse1
	        ports:
	            - 9001:9000
	        volumes:
	                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
	                - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
	                - ./config/macros/macros1.xml:/etc/clickhouse-server/config.d/macros.xml
	                - ./config/users.xml:/etc/clickhouse-server/users.xml
	                # - ./data/server1:/var/lib/clickhouse
	        ulimits:
	            nofile:
	                soft: 262144
	                hard: 262144
	        depends_on:
	            - "clickhouse-zookeeper"
	

	    clickhouse2:
	        image: yandex/clickhouse-server
	        hostname: clickhouse2
	        container_name: clickhouse2
	        ports:
	            - 9002:9000
	        volumes:
	                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
	                - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
	                - ./config/macros/macros2.xml:/etc/clickhouse-server/config.d/macros.xml
	                - ./config/users.xml:/etc/clickhouse-server/users.xml
	                # - ./data/server2:/var/lib/clickhouse
	        ulimits:
	            nofile:
	                soft: 262144
	                hard: 262144
	        depends_on:
	            - "clickhouse-zookeeper"
	

	    clickhouse3:
	        image: yandex/clickhouse-server
	        hostname: clickhouse3
	        container_name: clickhouse3
	        ports:
	            - 9003:9000
	        volumes:
	                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
	                - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
	                - ./config/macros/macros3.xml:/etc/clickhouse-server/config.d/macros.xml
	                - ./config/users.xml:/etc/clickhouse-server/users.xml
	                # - ./data/server3:/var/lib/clickhouse
	        ulimits:
	            nofile:
	                soft: 262144
	                hard: 262144
	        depends_on:
	            - "clickhouse-zookeeper"
	

	    clickhouse4:
	        image: yandex/clickhouse-server
	        hostname: clickhouse4
	        container_name: clickhouse4
	        ports:
	            - 9004:9000
	        volumes:
	                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
	                - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
	                - ./config/macros/macros4.xml:/etc/clickhouse-server/config.d/macros.xml
	                - ./config/users.xml:/etc/clickhouse-server/users.xml
	                # - ./data/server4:/var/lib/clickhouse
	        ulimits:
	            nofile:
	                soft: 262144
	                hard: 262144
	        depends_on:
	            - "clickhouse-zookeeper"
	

	    clickhouse5:
	        image: yandex/clickhouse-server
	        hostname: clickhouse5
	        container_name: clickhouse5
	        ports:
	            - 9005:9000
	        volumes:
	                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
	                - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
	                - ./config/macros/macros5.xml:/etc/clickhouse-server/config.d/macros.xml
	                - ./config/users.xml:/etc/clickhouse-server/users.xml
	                # - ./data/server5:/var/lib/clickhouse
	        ulimits:
	            nofile:
	                soft: 262144
	                hard: 262144
	        depends_on:
	            - "clickhouse-zookeeper"
	

	    clickhouse6:
	        image: yandex/clickhouse-server
	        hostname: clickhouse6
	        container_name: clickhouse6
	        ports:
	            - 9006:9000
	        volumes:
	                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
	                - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
	                - ./config/macros/macros6.xml:/etc/clickhouse-server/config.d/macros.xml
	                - ./config/users.xml:/etc/clickhouse-server/users.xml
	                # - ./data/server6:/var/lib/clickhouse
	        ulimits:
	            nofile:
	                soft: 262144
	                hard: 262144
	        depends_on:
	            - "clickhouse-zookeeper"
	networks:
	    default:
	        external:
	            name: clickhouse-net

